#
# Your Crowdin credentials
#
"project_id": "5"
"base_path": "."
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_url_env": "CROWDIN_BASE_URL"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files:
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  - source: "/libs/**/locale/strings.json"
    # Where translations will be placed
    # e.g. "/locale/%two_letters_code%/%original_file_name%"
    translation: "/%original_path%/translations/%locale%.json"
    export_only_approved: true
    skip_untranslated_strings: true
  - source: "/libs/**/locale/strings.yml"
    # Where translations will be placed
    # e.g. "/locale/%two_letters_code%/%original_file_name%"
    translation: "/%original_path%/translations/%locale%.yml"
    export_only_approved: true
    skip_untranslated_strings: true
